.TH "Interface" 3 "Sun Feb 14 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Interface
.SH SYNOPSIS
.br
.PP
.PP
Inherits JFrame\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCloseAction\fP"
.br
.ti -1c
.RI "class \fBListAction\fP"
.br
.ti -1c
.RI "class \fBPlayAction\fP"
.br
.ti -1c
.RI "class \fBSearchAction\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
